import { SidebarProvider } from "@/components/ui/sidebar";
import "../styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { SidebarNav } from "@/components/sidebar-nav";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <SidebarProvider>
          <div className="flex min-h-screen">
            <SidebarNav />
            <main className="flex-1 p-8">{children}</main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
